export const FALLBACK_MARKETS = [
  {
    id: 1,
    name: 'Lincoln Park Farmers Market',
    neighborhood: 'Lincoln Park, Chicago',
    address: 'Armitage Ave & Orchard St',
    operatingDays: 'Every Saturday',
    openingHours: '08:00 AM - 01:00 PM',
    active_stalls_count: 24,
    specialty: 'Organic Vegetables, Heirloom Tomatoes & Artisan Dairy',
  },
  {
    id: 2,
    name: 'Green City Market',
    neighborhood: 'Lincoln Park South, Chicago',
    address: '1817 N Clark St',
    operatingDays: 'Wed & Saturday',
    openingHours: '07:00 AM - 01:00 PM',
    active_stalls_count: 36,
    specialty: 'Orchard Fruits, Sweet Berries & Pastured Eggs',
  },
  {
    id: 3,
    name: 'Logan Square Farmers Market',
    neighborhood: 'Logan Square, Chicago',
    address: '3107 W Logan Blvd',
    operatingDays: 'Every Sunday',
    openingHours: '08:30 AM - 02:00 PM',
    active_stalls_count: 30,
    specialty: 'Artisan Sourdough, Raw Wildflower Honey & Microgreens',
  },
];

export const FALLBACK_HARVEST = [
  {
    id: 1,
    name: 'Organic Heirloom Tomatoes',
    category: { name: 'Vegetables' },
    farmOrigin: 'Green Valley Organics',
    marketName: 'Lincoln Park Market',
    price: 4.5,
    unit: 'lb',
    tag: 'USDA Organic',
    description: 'Harvested fresh this morning at 05:30 AM at peak sugar content.',
    avg_rating: 4.9,
    review_count: 38,
    stock_quantity: 18,
  },
  {
    id: 2,
    name: 'Crisp Honeycrisp Apples',
    category: { name: 'Fruits' },
    farmOrigin: 'Sunny Ridge Orchards',
    marketName: 'Green City Market',
    price: 3.8,
    unit: 'lb',
    tag: 'Tree Ripened',
    description: 'Hand-picked from 25-year mature orchard with crisp sweet bite.',
    avg_rating: 4.95,
    review_count: 52,
    stock_quantity: 35,
  },
  {
    id: 3,
    name: 'Raw Wildflower Honey Comb',
    category: { name: 'Honey & Pantry' },
    farmOrigin: 'Prairie Blossom Apiary',
    marketName: 'Logan Square Market',
    price: 12.0,
    unit: 'jar',
    tag: 'Pure & Raw',
    description: 'Single-source raw nectar with comb slice, unfiltered and pure.',
    avg_rating: 5.0,
    review_count: 44,
    stock_quantity: 8,
  },
  {
    id: 4,
    name: 'Pastured Free-Range Eggs',
    category: { name: 'Dairy & Eggs' },
    farmOrigin: 'Oakwood Farmsteads',
    marketName: 'Lincoln Park Market',
    price: 6.5,
    unit: 'dozen',
    tag: 'Pasture Raised',
    description: 'Foraged on open clover grass daily with rich golden yolks.',
    avg_rating: 4.92,
    review_count: 29,
    stock_quantity: 20,
  },
  {
    id: 5,
    name: 'Artisan Sourdough Country Loaf',
    category: { name: 'Bakery' },
    farmOrigin: 'Stone Ground Craft Bakery',
    marketName: 'Logan Square Market',
    price: 7.0,
    unit: 'loaf',
    tag: '36-Hr Fermented',
    description: 'Stone-milled organic wheat, wild sourdough yeast, crispy crust.',
    avg_rating: 4.98,
    review_count: 67,
    stock_quantity: 6,
  },
  {
    id: 6,
    name: 'Sweet Tender Baby Spinach',
    category: { name: 'Vegetables' },
    farmOrigin: 'River Valley Greens',
    marketName: 'Green City Market',
    price: 3.2,
    unit: 'bundle',
    tag: 'Pesticide Free',
    description: 'Triple washed and hydro-cooled for long-lasting crispness.',
    avg_rating: 4.88,
    review_count: 23,
    stock_quantity: 25,
  },
];
